.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MAGISTRATE" "1" "August 2011" "Magistrate 0.1.0" "Magistrate Manual"
.
.SH "NAME"
\fBmagistrate\fR \- clustered worker process manager
.
.SH "SYNOPSIS"
\fBmagistrate\fR
.
.SH "DESCRIPTION"
\fBMagistrate\fR is a manager for workers that is cluster and network aware\.
.
.br
It interacts with a centralized server to get its management and marching orders\.
.
.IP "\(bu" 4
It runs entirely in userland\.
.
.IP "\(bu" 4
All config data is stored in ~/\.magistrate
.
.IP "" 0
.
.SH "RUNNING"
\fBmagistrate start\fR is used to run your application directly from the command line\.
.
.SH "COPYRIGHT"
Foreman is Copyright (C) 2011 Drew Blas \fIdrew\.blas@gmail\.com\fR
